### ISSUE TITLE
Can not make it work

### ISSUE THREAD

**Issue by goto3** [devias-io/material-kit-react#112]
Hello, 

When I try to run this react project it gives me these errors:

```
info  - Checking validity of types
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
[    ] info  - Generating static pages (0/9)
Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:18:327)
    at Object.exports.useContext (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:22:269)
    at Head (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\next\dist\shared\lib\head.js:170:34)
    at d (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at renderPage (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\server\render.js:686:46)
    at Object.ctx.renderPage (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\.next\server\pages\_document.js:102:26)

Error occurred prerendering page "/account". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:18:327)
    at Object.exports.useContext (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:22:269)
    at Head (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\next\dist\shared\lib\head.js:170:34)
    at d (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at renderPage (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\server\render.js:686:46)
    at Object.ctx.renderPage (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\.next\server\pages\_document.js:102:26)

Error occurred prerendering page "/products". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:18:327)
    at Object.exports.useContext (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:22:269)
    at Head (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\next\dist\shared\lib\head.js:170:34)
    at d (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at renderPage (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\server\render.js:686:46)
    at Object.ctx.renderPage (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\.next\server\pages\_document.js:102:26)

Error occurred prerendering page "/settings". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:18:327)
    at Object.exports.useContext (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:22:269)
    at Head (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\next\dist\shared\lib\head.js:170:34)
    at d (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at renderPage (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\server\render.js:686:46)
    at Object.ctx.renderPage (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\.next\server\pages\_document.js:102:26)

Error occurred prerendering page "/login". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:18:327)
    at Object.exports.useContext (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:22:269)
    at Head (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\next\dist\shared\lib\head.js:170:34)
    at d (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at renderPage (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\server\render.js:686:46)
    at Object.ctx.renderPage (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\.next\server\pages\_document.js:102:26)

Error occurred prerendering page "/register". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:18:327)
    at Object.exports.useContext (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:22:269)
    at Head (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\next\dist\shared\lib\head.js:170:34)
    at d (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at renderPage (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\server\render.js:686:46)
    at Object.ctx.renderPage (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\.next\server\pages\_document.js:102:26)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:18:327)
    at Object.exports.useContext (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:22:269)
    at Head (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\next\dist\shared\lib\head.js:170:34)
    at d (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at renderPage (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\server\render.js:686:46)
    at Object.ctx.renderPage (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\.next\server\pages\_document.js:102:26)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:18:327)
    at Object.exports.useContext (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:22:269)
    at Head (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\next\dist\shared\lib\head.js:170:34)
    at d (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at renderPage (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\server\render.js:686:46)
    at Object.ctx.renderPage (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\.next\server\pages\_document.js:102:26)

Error occurred prerendering page "/customers". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:18:327)
    at Object.exports.useContext (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\react\cjs\react.production.min.js:22:269)
    at Head (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\node_modules\next\dist\shared\lib\head.js:170:34)
    at d (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (C:\Users\goto\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at renderPage (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\server\render.js:686:46)
    at Object.ctx.renderPage (C:\Users\goto\Documents\Proyectos\Equipos 2021\Frontend\.next\server\pages\_document.js:102:26)
info  - Generating static pages (9/9)

> Build error occurred
Error: Export encountered errors on following paths:
        /
        /404
        /_error: /500
        /account
        /customers
        /login
        /products
        /register
        /settings
    at C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\export\index.js:500:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\trace\trace.js:74:20)
    at async C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\build\index.js:987:17
    at async Span.traceAsyncFn (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\trace\trace.js:74:20)
    at async C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\build\index.js:861:13
    at async Span.traceAsyncFn (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\trace\trace.js:74:20)
    at async Object.build [as default] (C:\Users\goto\AppData\Roaming\npm\node_modules\next\dist\build\index.js:82:25)
```

**System:** 

- Node.js 16
- Installed next 12.0.7 globally

**Commands executed:**

npm i
next build

**Comment by goto3** [comment]
`npm run dev` is the command to run
